### ISSUE TITLE
Timestamps are not imported correctly using Influx Line Protocol

### ISSUE THREAD

**Issue by jphavoc** [questdb/questdb#1182]
**Describe the bug**
 
Importing a row with less values as its predecessor, causes an incorrect timestamp for that row. The timestamp of the row will be the same as the one of its predecessor. 
 
**To Reproduce**

1. Import data set via ILP (using Python 3.9.5)
```python
import socket


host = 'localhost'
port = 9001
table = 'table1'
data = [
    f'{table} windspeed=1.0 631152015679140000',
    f'{table} windspeed=2.0 631152015988640000',
    f'{table} timetocycle=0.0,windspeed=3.0 631152016248640000',
    f'{table} windspeed=4.0 631163016248640000',
    f'{table} windspeed=5.0 642152016258640000',
]

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    sock.connect((host, port))
    for row in data:
        sock.sendall((row + '\n').encode())
```

2. Query data and verify (http://localhost:9000)

```sql
select * from table1
```

 and 

```sql
select distinct timestamp from table1
```

and

```sql
select cast(timestamp as LONG) from table1
```

**Expected behavior**

Timestamps should be imported correctly.

All timestamps of the imported data should be different. However, row 3 and 4 have the same timestamp.

Written data is expected to be

```
"windspeed","timestamp","timetocycle"
1.0,"1990-01-01T00:00:15.679140Z",
2.0,"1990-01-01T00:00:15.988640Z",
3.0,"1990-01-01T00:00:16.248640Z",0.0  
4.0,"1990-01-01T03:03:36.248640Z",
5.0,"1990-05-08T07:33:36.258640Z",
```

but instead is

```
"windspeed","timestamp","timetocycle"
1.0,"1990-01-01T00:00:15.679140Z",
2.0,"1990-01-01T00:00:15.988640Z",
3.0,"1990-01-01T00:00:16.248640Z",0.0   <---- 
4.0,"1990-01-01T00:00:16.248640Z",  <----
5.0,"1990-05-08T07:33:36.258640Z",
```

**Environment**
 - OS: MacOS
 - QuestDB Version 6.0.3
 -  Using official Helm Chart with values
```yaml
image:
  repository: questdb/questdb
  pullPolicy: IfNotPresent
  tag: 6.0.3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

questdb:
  config:
    enabled: true
    options:
      shared.worker.count: 8
      http.min.enabled: true
      telemetry.enabled: false
      line.tcp.max.uncommitted.rows: 1000
      line.tcp.maintenance.job.interval: 500
      line.tcp.timestamp: n

service:
  annotations: {}
  type: NodePort
  port: 9000
  expose:
    postgresql:
      enabled: false
      port: 8812
    influxdb:
      enabled: true
      port: 9009

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: manual

ingress:
  enabled: false
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
```
