### ISSUE TITLE
SQL Query:  ORDER BY DESC LIMIT N not returning expected number of rows

### ISSUE THREAD

**Issue by andyb-ev** [questdb/questdb#3163]
### Describe the bug

Similar to https://github.com/questdb/questdb/issues/3081

A very similar repro is provided which does some inserts then some queries using various `ORDER BY` and `LIMIT` clauses.

Using `ORDER BY timestamp DESC LIMIT <N>` can lead to only getting 1 result back instead of the expected number of rows back.

### To reproduce

**Docker Compose:**
```
---
version: '3'

services:
  questdb:
    image: questdb/questdb:nightly
    container_name: questdb
    restart: unless-stopped
    environment:
      QDB_STRICT_VALIDATION: 'true'
      QDB_METRICS_ENABLED: 'true'
      QDB_LINE_TCP_DEFAULT_PARTITION_BY: 'HOUR'
      QDB_LINE_DEFAULT_PARTITION_BY: 'HOUR'
      QDB_CAIRO_WAL_ENABLED_DEFAULT: 'false'
    volumes:
      - questdb-data:/var/lib/questdb
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"

volumes:
  questdb-data:
```

See attached repro Java code

[QuestDbSortDescRepro.java.txt](https://github.com/questdb/questdb/files/11162988/QuestDbSortDescRepro.java.txt)

### Expected Behavior

**Expected:**
```
 -- QUERY RESULTS -- 
  count(*)       = [2000]
  descCount      = [500]
  descLimitCount = [500]
  ascCount       = [500]
  ascLimitCount  = [500]
  allEqual       = [true]
 -----------------
 ```
 
 **Actual:**
 ```
  -- QUERY RESULTS -- 
  count(*)       = [2000]
  descCount      = [500]
  descLimitCount = [1]
  ascCount       = [500]
  ascLimitCount  = [500]
  allEqual       = [false]
 -----------------
 ```

### Environment

```markdown
- **QuestDB version**: nightly (as of 2023-04-05)
- **OS**: Docker Image
- **Browser**: N/A (Java ILP Sender Client, Java JDBC/Postgres Query)
```
