### ISSUE TITLE
Unable to retrieve data from Grafana

### ISSUE THREAD

**Issue by aizzi** [questdb/questdb#3640]
### Describe the bug

I'm new to QuestDB and I'm exploring the possibility to connect it to Grafana. I'm using the following Docker compose file to test the two:

```
version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:10.0.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
  questdb:
    image: questdb/questdb:7.3
    container_name: questdb
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
    environment:
      - QDB_PG_READONLY_USER_ENABLED=true
      - QDB_PG_SELECT_CACHE_ENABLED=false
    volumes:
      - "questdb_storage:/var/lib/questdb"
volumes:
  grafana_storage: {}
  questdb_storage: {}
```

In Grafana I created the datasource for QuestDB, following the instructions [here](https://questdb.io/blog/time-series-monitoring-dashboard-grafana-questdb/). I have no problem in creating the data source, and Grafana connects to QuestDB as you can see in the attached screenshot.

However, when I try to run a query against it, I'm unable to retrieve the information from the database. I cannot see the tables in there. The `Table` field to select the table reports "No options found".

When I look at the QuestDB logs, I can see the connection followed by this error:

```
2023-08-11T14:07:49.327721Z I pg-server connected [ip=172.26.0.2, fd=155]
2023-08-11T14:07:49.330897Z I i.q.g.SqlCompiler parse [fd=-1, q=select quote_ident(table_name) as "table" from information_schema.tables
    where quote_ident(table_schema) not in ('information_schema',
                             'pg_catalog',
                             '_timescaledb_cache',
                             '_timescaledb_catalog',
                             '_timescaledb_internal',
                             '_timescaledb_config',
                             'timescaledb_information',
                             'timescaledb_experimental')
      and
          quote_ident(table_schema) IN (
          SELECT
            CASE WHEN trim(s[i]) = '"$user"' THEN user ELSE trim(s[i]) END
          FROM
            generate_series(
              array_lower(string_to_array(current_setting('search_path'),','),1),
              array_upper(string_to_array(current_setting('search_path'),','),1)
            ) as i,
            string_to_array(current_setting('search_path'),',') s
          )]
2023-08-11T14:07:49.331050Z E i.q.c.p.PGConnectionContext error [pos=817, msg=`unknown function name: current_setting(STRING)`]
```

### To reproduce

1. `docker compose up -d`
2. Populate the database (I think it doesn't matter what you put in it)
3. Open Grafana
4. Configure the DataSource as described in the attached image (username and password are the default ones)
5. Test for successful connection from Grafana
6. Open the "Explore" view
7. In the `Table` field there are no tables reported
8. Check the `questdb` container logs

### Expected Behavior

Information are retrieved from QuestDB

### Environment

```markdown
- **QuestDB version**: 7.3
- **Grafana version**: 10.0.3
- **OS**: N/A
- **Browser**: Firefox 116.0.2
```

### Additional context

![datasource](https://github.com/questdb/questdb/assets/23487265/305863bd-1bd2-4988-b836-5653f06dafab)
![console](https://github.com/questdb/questdb/assets/23487265/6ef3adf8-b964-4c9e-b12c-67514f9c1bfa)
