### ISSUE TITLE
max_map_count default is low for QuestDB deployed via Helm Chart

### ISSUE THREAD

**Issue by peterklingelhofer** [questdb/questdb#4854]
### To reproduce

How can i increase vm.max_map_count=1048576 in QuestDB deployed via helm chart? I see this warning immediately after upgrading:

![Screenshot 2024-08-07 at 2 43 19 PM](https://github.com/user-attachments/assets/6cca0695-e715-4822-ae71-6f4c34d88e9e)

Is this possible to set in the Helm chart, or must this be done at the Kubernetes level?

### QuestDB version:

8.1.0

### OS, in case of Docker specify Docker and the Host OS:

Default helm chart (https://artifacthub.io/packages/helm/questdb/questdb)

### File System, in case of Docker specify Host File System:

Amazon EBS disk

### Full Name:

Peter Klingelhofer

### Affiliation:

Energy Vault

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

I realize this is discussed [here](https://questdb.io/docs/deployment/capacity-planning/#max-virtual-memory-areas-limit), but is there a way to change this from the helm chart itself? We've changed other values in the configuration but I don't see this one listed: https://questdb.io/docs/configuration/#cairo-engine. Thank you!

**Comment by peterklingelhofer** [comment]
Nevermind, it would appear that this has to be changed at the Kubernetes level:

"vm.max_map_count is actually a https://docs.actian.com/vector/5.0/index.html#page/User/Increase_max_map_count_Kernel_Parameter_(Linux).htm, so you will need to modify your node directly in order to change this setting. Some k8s service providers, like Azure, easily allow you to customize these kernel parameters."

**Comment by peterklingelhofer** [comment]
For those curious how to do this via Helm charts, & AWS EKS you can do this via applying a daemonset such as this example: https://github.com/awslabs/amazon-eks-ami/issues/184#issuecomment-1267522828

**Comment by peterklingelhofer** [comment]
Now that the 0.40.50 [helm chart](https://artifacthub.io/packages/helm/questdb/questdb) supports `initContainers`, this is really easy to achieve using a busybox with no volume mounts. Kudos to the QuestDB team for adding this so quickly:

```yaml
initContainers:
  - name: sysctl
    image: busybox:latest
    command:
      - sh
      - -c
      - |
        sysctl -w vm.max_map_count=16777216 && sysctl -w fs.file-max=16777216
    securityContext:
      privileged: true
    volumeMounts: []
```
