### ISSUE TITLE
docker-compose issue with inserting data into WAL tables

### ISSUE THREAD

**Issue by nwoolmer** [questdb/questdb#5124]
### To reproduce

Set up docker.

Take this `docker-compose.yml`:

```yaml
services:
  historic-data:
    image: questdb/questdb:8.1.4
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
    volumes:
      - "P:/volume/questdb:/var/lib/questdb"
 ```
Change the volume to something appropriate on your machine.

Start the database.

Create a table:

```sql
create table foo (
  symbol symbol,
  tenant symbol,
  source symbol,
  ask double,
  bid double,
  value double,
  state long,
  entity long,
  timestamp timestamp
) timestamp(timestamp) partition by day wal;
```

Insert data:

```sql
insert into foo values ('USD', 'examp', 'api', 1, 2, 3, 4, 5, now())
```

Observe that the numeric values have become 0:

![image](https://github.com/user-attachments/assets/8ba93c63-6ea3-4efb-a81b-138c3e04b26b)

Not reproducible in 8.0.3 down to 8.0.0.

### QuestDB version:

8.1.0+

### OS, in case of Docker specify Docker and the Host OS:

Docker Windows 11 WSL2

### File System, in case of Docker specify Host File System:

NTFS and ReFS

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have
