### ISSUE TITLE
After restarting the server, the table data is gone.

### ISSUE THREAD

**Issue by downdawn** [questdb/questdb#5358]
### To reproduce

docker-compose.yml
```
services:
  questdb:
    image: questdb/questdb:8.2.1
    container_name: questdb
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9003:9003"
      - "9009:9009"
    environment:
      - QDB_METRICS_ENABLED=TRUE
    volumes:
      - ./questdb_data:/var/lib/questdb
      - ./conf:/conf
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

volumes:
  prometheus_data:
```

sudo docker-compose up -d

### QuestDB version:

8.2.1

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu22.04（docker）

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

dylan

### Affiliation:

xkg

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

![Image](https://github.com/user-attachments/assets/7dc95b4d-095e-4855-8e23-b9c161122064)

![Image](https://github.com/user-attachments/assets/a3bb0757-a05c-48c4-9da9-279f4e8bb73a)

![Image](https://github.com/user-attachments/assets/37b85a17-0710-4ea1-9313-8e1a4dd91dd4)
